name: Build and distribute

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: AlTeveDev/action-wasmpack-build-pages@main
